Add code of conduct
lyonjug/lyonjug.org pull request #36
Opened 2020-01-29 19:43 UTC by gquintana

2020-01-29 20:18 UTC, clvi commented on coc.html
> +      Nous voulons être très clairs pour tou.te.s les participants, conférenciers
Si tu mets "tou.te.s", ne faut il pas aussi mettre "participant.e.s" et "conférencier.e.s", par cohérence ?

2020-01-29 20:18 UTC, clvi commented on coc.html
> +    <p>Qui contacter&nbsp;? Directement à un des membres de l'équipe du LyonJUG,
"directement un des membres de l'équipe", sans "à" je pense ?

2020-01-29 20:18 UTC, clvi commented on _layouts/default.html
> +                <a class="nav-item nav-link" href="/coc.html">CoC</a>
Par cohérence avec le reste du site qui est majoritairement en français, et pour être plus explicite, est-ce qu'il ne serait pas mieux de mettre "Code de conduite"? Ou est-ce que ça fait moche dans le header?

2020-01-30 09:48 UTC, mazerty commented
tu t'es inspiré d'un coc existant ? si oui, il vaut mieux le mentionner non ?

2020-01-31 12:06 UTC, gquintana commented on _layouts/default.html
> +                <a class="nav-item nav-link" href="/coc.html">CoC</a>
Je ne voulais pas que ce soit trop visible sur la page d'accueil. Je n'ai pas mis CdC à la française parce que ca fait trop Cahier des Charges.

2020-01-31 12:07 UTC, gquintana commented
> 
> 
> tu t'es inspiré d'un coc existant ? si oui, il vaut mieux le mentionner non ?

Oui j'ai repris celui du ToursJUG https://www.toursjug.org/coc/ qui est visiblement une traduction de celui du VirtualJUG https://virtualjug.com/coc

2020-02-02 14:48 UTC, gquintana commented
@mazerty @clvi J'ai repris pas mal de choses.

2020-02-02 15:40 UTC, clvi commented on coc.html
> +        de l'événement. Par conséquent, tout participant auquel on demande de cesser
"tout participant à qui il est demandé de... "

2020-02-02 15:40 UTC, clvi commented on coc.html
> +    <p>Si vous sentez harcelé ou remarquez que quelqu’un d’autre est harcelé,
"si vous vous sentez harcelé.e"?

2020-02-02 19:01 UTC, clvi approved these changes

2020-02-03 15:24 UTC, mazerty requested changes

2020-02-03 15:24 UTC, mazerty commented on coc.html
> +    <p>Les événements LyonJUG doivent rester doivent rester un moment agréable
"doivent rester" en double

2020-02-03 15:24 UTC, mazerty commented on coc.html
> +        et plaisant pour tous et toutes, indépendamment du genre, de l’orientation sexuelle,
"des moments agréables et plaisants"
pour accorder avec "Les évènements LyonJUG"

2020-02-03 15:24 UTC, mazerty commented on coc.html
> +         <li>par DM Twitter <a href="https://twitter.com/lyonjug">@LyonJUG</a>,</li>
le rendu des "li" n'est pas top du tout, il faudrait revoir

2020-02-03 15:24 UTC, mazerty commented on coc.html
> +     <p>Cette page est un traduction libre de
"une" traduction

2020-02-03 15:25 UTC, mazerty commented
tu as essayé de le faire en markdown plutôt ?

2020-02-04 20:26 UTC, gquintana commented on coc.html
> +         <li>par DM Twitter <a href="https://twitter.com/lyonjug">@LyonJUG</a>,</li>
AMHA Ce n'est pas très grave si c'est moche

2020-02-19 16:02 UTC, mazerty commented
là aussi j'ai pushé deux commits mais la pr a été mise à jour par contre ^^'

2020-02-20 06:48 UTC, mazerty approved these changes

2020-02-21 08:43 UTC, merged