Add Azure Meetup
lyonjug/lyonjug.org pull request #38
Opened 2020-02-04 20:36 UTC by gquintana

2020-02-04 20:43 UTC, clvi requested changes

2020-02-04 20:43 UTC, clvi commented on _posts/2020-03-23-springboot-azure.md
> +meetup-event-id: "TODO"
C'est mieux de ne pas mettre cette ligne plutôt que de mettre TODO, ça masque les boutons d'inscription, alors que sinon ça génère des liens cassés c'est pas ouf...

2020-02-04 20:48 UTC, gquintana commented on _posts/2020-03-23-springboot-azure.md
> +meetup-event-id: "TODO"
Mon idée était plutot de créer le meetup...

2020-02-09 16:26 UTC, gquintana commented on _posts/2020-03-23-springboot-azure.md
> +meetup-event-id: "TODO"
J'ai prépare le meetup et mis l'ID dans la PR

2020-02-09 16:59 UTC, clvi approved these changes

2020-02-19 15:59 UTC, mazerty commented
dseds

2020-02-20 07:00 UTC, mazerty approved these changes

2020-02-20 07:00 UTC, mazerty commented
il faudra merger en même temps que la comm' sinon il y aura une 404 pour l'évènement tant qu'il n'est pas public je pense

2020-03-03 05:40 UTC, merged